### PR TITLE
Feature branch ready to review

### PR DESCRIPTION
**Pull request by Daniduran-dev**
I have already finished the project and I'm asking for a review to merge it to the master branch.

### CODE REVIEW

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi, @Daniduran-dev nice attempt 👍 . We are missing some basic requirements for this project. Find the comments below. Kindly treat every comment as **IMPORTANT**.
- We are missing one important basic requirement ```README``` file. Check [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Template for README[template](https://github.com/microverseinc/readme-template)
- We are failing stickler checks.
la
- Our commits should describe what we did building the project. Example: ``` added links to header```.
la1
- Our PR should have a title and a short summary. [More](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
**THESE ARE THE HARD REQUIREMENTS. ALL PROJECTS WILL BE MARKED AS INVALID SHOULD YOU FAIL TO MEET THEM**
**Kindly fix the following project specifications**
- Currently, we do not have a navbar. Let us create one and insert the nine buttons in style them as required.
la2
- Currently, we are missing the ```bottom```. Kindly add the four links as describe in the project specification
la3
- Currently, we do not have a ```<footer>```. Check image below
la4
- Currently, we have an image but it should be a ```<div>``` with a class and give it a background or background-url as seen below:
la5

- **Note** Apply background-gradient to the nav as described in the project specifications
la6


Make all these changes and submit another code review. 😄 
Happy coding 💻 
Daniel Larbi Addo

**Comment by Daniduran-dev** [comment]
Hello Daniel, How can I see those requirements? I cantt find them. I just have the odin project link.  As you see it doesn’t says anything about nine buttons and the rest of things you told me. Maybe there is a problem from Microverse here. Please send me the link to all these project specifications and I will contact the success team to inform about this issue. Thank you for your help,Daniel From: Daniel Larbi AddoSent: 25 February 2020 01:03To: Daniduran-dev/apple-clone-soloCc: Daniduran-dev; MentionSubject: Re: [Daniduran-dev/apple-clone-solo] Feature -stickler- (#2) @addod19 requested changes on this pull request.Status: Require changes 🔴Hi, @Daniduran-dev nice attempt 👍 . We are missing some basic requirements for this project. Find the comments below. Kindly treat every comment as IMPORTANT.We are missing one important basic requirement README file. Check here. Template for READMEtemplateWe are failing stickler checks.Our commits should describe what we did building the project. Example: added links to header.Our PR should have a title and a short summary. MoreTHESE ARE THE HARD REQUIREMENTS. ALL PROJECTS WILL BE MARKED AS INVALID SHOULD YOU FAIL TO MEET THEMKindly fix the following project specificationsCurrently, we do not have a navbar. Let us create one and insert the nine buttons in style them as required.Currently, we are missing the bottom. Kindly add the four links as describe in the project specificationCurrently, we do not have a <footer>. Check image belowCurrently, we have an image but it should be a <div> with a class and give it a background or background-url as seen below:Note Apply background-gradient to the nav as described in the project specificationsMake all these changes and submit another code review. 😄Happy coding 💻Daniel Larbi Addo—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Daniduran-dev** [comment]
Hello,
I have already made a readme file and use buttons in the navbar. As well as fixed the stickler requirements. What I don't know hot to change is the pull request title and short summary, I think it's impossible to do it once the pull request is already created.
I need to have access to all the requirements for this project otherwise I can't progress. I can't see any of the requirements you showed me either on Microverse or Odin Project.
I don't know what is the "bottom" so I can't do anything about it.
Also there was already a footer in my html.
I don't know what is that image that should be a div with a background image. Please be more specific or i will not be able to identify the problem.
And finally, my navbar had already a background gradient that matches the original site gradient.

Thanks fore the review,
Daniel

**Comment by addod19** [comment]
> Hello,
> I have already made a readme file and use buttons in the navbar. As well as fixed the stickler requirements. What I don't know hot to change is the pull request title and short summary, I think it's impossible to do it once the pull request is already created.
> I need to have access to all the requirements for this project otherwise I can't progress. I can't see any of the requirements you showed me either on Microverse or Odin Project.
> I don't know what is the "bottom" so I can't do anything about it.
> Also there was already a footer in my html.
> I don't know what is that image that should be a div with a background image. Please be more specific or i will not be able to identify the problem.
> And finally, my navbar had already a background gradient that matches the original site gradient.
> 
> Thanks fore the review,
> Daniel

Hi Daniduran, you can edit the PR. The 3 dot(...) next to the imoji icon. Click on it and select edit. The bottom part is the four columns on the apple page. It is an image and should be clickable. There should be no image tag in the html file. It should be a div and set background in css file. I hope my explanations are clear now. Reach me on slack Daniel Larbi Addo

**Comment by Daniduran-dev** [comment]
I have already modified the site with background images instead of images

**Comment by Daniduran-dev** [comment]
I have already change the alphabetical order of the elements. When i did it it change the aspect of my site so i had to fix it again. The stickler is still saying weird stuff, but the site works perfectly. I don't understand why i can't use width with borders.. it doesn't makes sense to me. Also i had to use important in some attributes or it wouldn't work.

**Pull request merged**
