### PR TITLE
Trying to get the official TSE team to review my code

### PR DESCRIPTION
**Pull request by Daniduran-dev**
I've been trying to review my code but nobody from the official TSE team has contacted me. I did merge my feature to my master. Why? because i thought i was talking to someone from TSE when it was just a man of Microverse helping me. A bit surreal situation but this is what happened.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :handshake:

**Comment by nikasulo** [comment]
# Hello @Daniduran-dev! :wave:
First, I read your PR description and I'd like to apologise for the delay in getting a TSE to review your work, this is not the norm at Microvese and as such I apologise! Your project is top of the line! It's really great, well written, styled and presented. Your readme file is also top notch, great work :handshake: :medal_military: I have a few suggestions, changes that are required to be made, please consider my comments below:

#### Stickler errors
You have done very nicely by including stickler in your project as requested! However, you need to ensure that all errors it throws are appropriately addressed before you request a PR review. Please look into this, address appropriately and request another review. 

#### HTML Validation
Please condsider parsing your HTML markup through this validator and correct all resulting errors. It is mandatory that your markup is free from semantic or syntax errors.
screenshot

### Summary
Big ups! Your performance on this project is exciting, make the required changes and request another review! I wish you the best and see you at the top! :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by Daniduran-dev** [comment]
Hello,

The stickler is not working anymore how can i fix it?

**Comment by Daniduran-dev** [comment]
Hello,
Is anybody there? I need help with the sticklers i've been stuck with the sticklers for 4 days now. Can we just forget about the sticklers and let me move on to the next project? I'm totally stuck and i don't see the solution. I just want to forget this nightmare.

**Comment by majovanilla** [comment]
### **Under Review by Maria Reyes**

**Comment by majovanilla** [comment]
Hey @Daniduran-dev , 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯
It looks very professional!!

- Good Readme template

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Let's make your checks pass on green. When you need help from us, you can reach out directly on Slack so we can better understand what the problem is. We don't usually see PR messages after we did the review.

- When asking for help, please make sure to tell us what's the exact problem you are having, what have you done to solve it and what do you need from us. Asking help in a general way is not a good option.

- The linters are showing that you don't have a two-space indentation, you have more. Do you have prettier or beautify installed? This can cause a lot of problems sometimes, due to its auto-indentation. Perhaps that's the problem.

- the error Expected empty line before rule (rule-empty-line-before) it's telling you that you need to leave a line before every time you declare a CSS style. Just hit enter.

When you have a linter error you don't understand, just copy it and google it, and you will find valuable resources to understand it better. Also, if you have VSCode, hover over it and it will give you more information.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Improve your Readme file. It should be descriptive of the project. 

-Please write meaningful pull request messages. Check this [example](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

- Remember the only moment when you are cleared to merge to master is when you see the Submit Project Button on your Dashboard!!

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by majovanilla** [comment]
Under Review By Maria Reyes

**Comment by majovanilla** [comment]
### Great work @Daniduran-dev !! 

Your project was great from the beginning and you made a great effort in solving the stickler errors.

You can merge with the master branch and submit the project completion form.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- It is a very good practice to include semantic HTML in your projects. The general structure you can follow is to create a `<nav>` element in your body (where the navbar goes) then a `<main>` element that encloses all the important content of your page, and then finish with the `<foooter>` tag.

### **Project has been approved** :heavy_check_mark: 

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Pull request merged**
